### ISSUE TITLE
An error maybe about system

### ISSUE THREAD

**Issue by Henry0132** [thu-ml/SRPO#1]
Hi!bro:
  As a green hand,I want to ask a problem.Could you tell me how to do it?
  When I use this code`$ TASK="halfcheetah-medium-v2"; seed=0; python3 -u train_behavior.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed}`,terminal tells me that `$ : 无法将“$”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
所在位置 行:1 字符: 33
+ $ TASK="halfcheetah-medium-v2"; seed=0; python3 -u train_behavior.py
    + CategoryInfo          : ObjectNotFound: (seed=0:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

I think that this error may be caused by system.My system is Windows10,and the environment is python3.7.
Your system may be Ubuntu20.04?

**Comment by ChenDRAG** [comment]
Hi, the first $ stands for the start of the command line. Try 
`TASK="halfcheetah-medium-v2"; seed=0; python3 -u train_behavior.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed}`
instead of 
`$ TASK="halfcheetah-medium-v2"; seed=0; python3 -u train_behavior.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed}`

**Comment by ChenDRAG** [comment]
I've updated the readme file to avoid similar confusion. Sorry for the inconvenience.

**Comment by Henry0132** [comment]
Thanks for your reply!Have a nice day!
